version: '3.1'
services:
  app:
    container_name: reactive-postgres
    image: reactive-postgres
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres